
"""FastAPI application for Yoga RAG Query API.

This API allows users to query the Pinecone vector database
and get answers generated by Groq LLM based on retrieved context.
"""

import os
import json
import re
import urllib.parse
import urllib.request
import uuid
from typing import List, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from langchain_groq import ChatGroq
from pinecone import Pinecone
from pydantic import BaseModel, Field
from sentence_transformers import SentenceTransformer

from prompt_temp import prompt as YOGA_PROMPT_TEMPLATE

# Load environment variables
load_dotenv()

# Initialize FastAPI app
app = FastAPI(
    title="Yoga RAG API",
    description="Query API for Yoga knowledge base using Pinecone vector search",
    version="1.0",
)

# Add CORS middleware for frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configuration
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME", "yoga-rag")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
PEXELS_API_KEY = os.getenv("PEXELS_API_KEY")
PORT = int(os.getenv("PORT", "8000"))
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
LLM_MODEL = "llama-3.3-70b-versatile"
PEXELS_SEARCH_URL = "https://api.pexels.com/v1/search"
POSE_BLOCK_HEADER = "POSES TO DISPLAY:"

# Global clients (initialized on startup)
embedding_model: Optional[SentenceTransformer] = None
pinecone_index = None
llm = None
pexels_cache = {}


class QueryRequest(BaseModel):
    question: str
    top_k: int = 3


class QueryResponse(BaseModel):
    id: str
    answer: str
    sources: List[str]
    isUnsafe: bool
    poses: List[dict] = Field(default_factory=list)


@app.on_event("startup")
def startup():
    """Initialize clients on startup."""
    global embedding_model, pinecone_index, llm

    # Initialize embedding model
    print("Loading embedding model...")
    embedding_model = SentenceTransformer(EMBEDDING_MODEL)
    print(f"Embedding model loaded: {EMBEDDING_MODEL}")

    # Initialize Pinecone
    print("Connecting to Pinecone...")
    pc = Pinecone(api_key=PINECONE_API_KEY)
    pinecone_index = pc.Index(PINECONE_INDEX_NAME)
    stats = pinecone_index.describe_index_stats()
    print(f"Connected to Pinecone index: {PINECONE_INDEX_NAME}")
    print(f"Total vectors: {stats.total_vector_count}")

    # Initialize LLM
    print("Initializing Groq LLM...")
    llm = ChatGroq(
        groq_api_key=GROQ_API_KEY,
        model_name=LLM_MODEL,
        temperature=0.1,
        max_tokens=1024,
    )
    print("LLM initialized")


def retrieve_documents(query: str, top_k: int = 3) -> List[dict]:
    """Retrieve relevant documents from Pinecone."""
    # Generate query embedding
    query_embedding = embedding_model.encode([query])[0].tolist()

    # Query Pinecone
    results = pinecone_index.query(
        vector=query_embedding,
        top_k=top_k,
        include_metadata=True,
    )

    documents = []
    for match in results.matches:
        metadata = match.metadata or {}
        documents.append(
            {
                "id": match.id,
                "content": metadata.get("text", ""),
                "source_file": metadata.get("source_file", ""),
                "page": metadata.get("page", 0),
                "similarity_score": match.score,
            }
        )

    return documents


def generate_answer(query: str, documents: List[dict]) -> str:
    """Generate answer using Groq LLM with retrieved context."""
    if not documents:
        return "No relevant information found to answer your question."

    # Build context from retrieved documents
    context = "\n\n".join(
        [f"Document {i + 1}: {doc['content']}" for i, doc in enumerate(documents)]
    )

    # Format and use imported prompt template
    prompt = YOGA_PROMPT_TEMPLATE.format(context=context, question=query)

    # Generate response
    response = llm.invoke(prompt)
    return response.content


def extract_sources(documents: List[dict]) -> List[str]:
    """Extract source information from documents."""
    sources = []
    for doc in documents:
        source = doc.get("source_file", "")
        page = doc.get("page", 0)
        if source:
            sources.append(f"{source} (page {page})")
    return sources


def parse_pose_line(line: str) -> dict | None:
    """Parse a line like '- Tree Pose | Vrksasana' into a pose dict."""
    # Remove bullet markers (-, *, 1., etc.)
    content = line.lstrip("-* 1234567890.").strip()

    # Split by | to separate English name from Sanskrit
    parts = [p.strip() for p in content.split("|", 1)]
    if not parts[0]:
        return None

    return {
        "name": parts[0],
        "sanskrit": parts[1] if len(parts) > 1 and parts[1].lower() != "unknown" else None
    }


def extract_inline_pose(line: str) -> dict | None:
    """Extract pose from inline text like 'Mountain Pose (Tadasana)'."""
    # Look for "Name (Sanskrit)" pattern
    match = re.search(r"([A-Z][A-Za-z0-9\s\-]+?)\s*\(([A-Za-z0-9\s\-]+?)\)", line)
    if not match:
        return None

    name = match.group(1).strip()
    sanskrit = match.group(2).strip()

    # Remove common sentence prefixes
    prefixes = ["to practice ", "for ", "try ", "do ", "the ", "into ", "is ", "called "]
    name_lower = name.lower()
    for prefix in prefixes:
        if name_lower.startswith(prefix):
            name = name[len(prefix):].strip()
            name_lower = name.lower()

    # Validate: must contain "pose" and not be too long
    if "pose" not in name_lower or len(name.split()) > 5:
        return None

    return {"name": name, "sanskrit": sanskrit}


def is_pose_header(line: str) -> bool:
    """Check if line is the 'POSES TO DISPLAY:' header."""
    return "poses to display" in line.lower()


def is_list_item(line: str) -> bool:
    """Check if line starts with a bullet or number."""
    return line.startswith(("- ", "* ", "1. ", "2. ", "3. ", "4. "))


def extract_pose_block(answer: str) -> tuple[List[dict], str]:
    """
    Extract pose names from LLM answer and remove the pose block.

    Args:
        answer: The raw LLM response text

    Returns:
        Tuple of (list of pose dicts, cleaned answer without pose block)
    """
    lines = answer.splitlines()
    poses = []
    seen_names = set()
    cleaned_lines = []
    skip_block = False

    for line in lines:
        stripped = line.strip()

        # Step 1: Detect "POSES TO DISPLAY:" header
        if is_pose_header(stripped):
            skip_block = True
            continue

        # Step 2: If inside pose block, parse pose lines
        if skip_block:
            # Empty line ends the block
            if stripped == "":
                skip_block = False
                continue

            # Parse bullet lines like "- Tree Pose | Vrksasana"
            if is_list_item(stripped):
                pose = parse_pose_line(stripped)
                if pose and pose["name"].lower() not in seen_names:
                    seen_names.add(pose["name"].lower())
                    poses.append(pose)
                continue

            # Non-list item means block ended
            skip_block = False

        # Step 3: Look for inline poses in regular text
        if not skip_block:
            pose = extract_inline_pose(stripped)
            if pose and pose["name"].lower() not in seen_names:
                seen_names.add(pose["name"].lower())
                poses.append(pose)

        # Step 4: Keep line for cleaned answer (if not in pose block)
        if not skip_block:
            cleaned_lines.append(line)

    cleaned_answer = "\n".join(cleaned_lines).strip()
    return poses[:4], cleaned_answer


def get_image_from_pexels(query: str) -> str | None:
    """Fetch a yoga pose image URL from Pexels API."""
    if not PEXELS_API_KEY:
        print("Pexels: No API key configured")
        return None

    # Check cache first
    cache_key = query.strip().lower()
    if cache_key in pexels_cache:
        return pexels_cache[cache_key]

    # Add "yoga pose" to query if not present
    search_query = query if "yoga" in query.lower() else f"{query} yoga pose"
    params = urllib.parse.urlencode({
        "query": search_query,
        "per_page": 1,
        "orientation": "portrait",
    })
    request = urllib.request.Request(
        f"{PEXELS_SEARCH_URL}?{params}",
        headers={"Authorization": PEXELS_API_KEY},
    )

    try:
        with urllib.request.urlopen(request, timeout=8) as response:
            data = json.loads(response.read().decode("utf-8"))
            photos = data.get("photos", [])

            if not photos:
                pexels_cache[cache_key] = None
                return None

            # Get best available image size
            src = photos[0].get("src", {})
            image_url = src.get("large") or src.get("medium") or src.get("portrait")
            pexels_cache[cache_key] = image_url
            return image_url

    except Exception as error:
        print(f"Pexels: Failed to fetch image for '{query}': {error}")
        pexels_cache[cache_key] = None
        return None


def build_pose_cards(poses: List[dict]) -> List[dict]:
    """Build pose cards with names only - frontend fetches images."""
    cards = []
    print(f"Extracted poses: {poses}")
    for pose in poses[:4]:
        cards.append(
            {
                "name": pose["name"],
                "sanskrit": pose.get("sanskrit"),
            }
        )

    print(f"Built pose cards: {cards}")
    return cards


@app.get("/")
def root():
    """Root endpoint."""
    return {
        "message": "Yoga RAG API",
        "docs": "/docs",
        "endpoints": {"query": "/query"},
    }


@app.get("/health")
def health():
    """Health check endpoint."""
    return {"status": "healthy"}


@app.post("/query", response_model=QueryResponse)
def query_endpoint(request: QueryRequest):
    """Query the yoga knowledge base.

    Args:
        request: QueryRequest with question string

    Returns:
        QueryResponse with generated answer and metadata
    """
    try:
        # Retrieve relevant documents
        documents = retrieve_documents(request.question, request.top_k)

        # Generate answer
        raw_answer = generate_answer(request.question, documents)
        pose_entries, answer = extract_pose_block(raw_answer)
        print(f"Pose entries parsed from LLM response: {pose_entries}")

        # Build response
        sources = extract_sources(documents)
        poses = build_pose_cards(pose_entries)

        return QueryResponse(
            id=str(uuid.uuid4()),
            answer=answer,
            sources=sources,
            isUnsafe=False,  # Can be enhanced with safety check
            poses=poses,
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=PORT)
