
"""FastAPI application for Yoga RAG Query API.

This API allows users to query the Pinecone vector database
and get answers generated by Groq LLM based on retrieved context.
"""

import os
import uuid
from typing import List, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from langchain_groq import ChatGroq
from pinecone import Pinecone
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer

from prompt_temp import prompt as YOGA_PROMPT_TEMPLATE

# Load environment variables
load_dotenv()

# Initialize FastAPI app
app = FastAPI(
    title="Yoga RAG API",
    description="Query API for Yoga knowledge base using Pinecone vector search",
    version="1.0",
)

# Add CORS middleware for frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configuration
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME", "yoga-rag")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
PORT = int(os.getenv("PORT", "8000"))
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
LLM_MODEL = "llama-3.3-70b-versatile"

# Global clients (initialized on startup)
embedding_model: Optional[SentenceTransformer] = None
pinecone_index = None
llm = None


class QueryRequest(BaseModel):
    question: str
    top_k: int = 3


class FeedbackRequest(BaseModel):
    questionId: str
    feedback: str


class QueryResponse(BaseModel):
    id: str
    answer: str
    sources: List[str]
    isUnsafe: bool
    poses: List[dict] = []


@app.on_event("startup")
def startup():
    """Initialize clients on startup."""
    global embedding_model, pinecone_index, llm

    # Initialize embedding model
    print("Loading embedding model...")
    embedding_model = SentenceTransformer(EMBEDDING_MODEL)
    print(f"Embedding model loaded: {EMBEDDING_MODEL}")

    # Initialize Pinecone
    print("Connecting to Pinecone...")
    pc = Pinecone(api_key=PINECONE_API_KEY)
    pinecone_index = pc.Index(PINECONE_INDEX_NAME)
    stats = pinecone_index.describe_index_stats()
    print(f"Connected to Pinecone index: {PINECONE_INDEX_NAME}")
    print(f"Total vectors: {stats.total_vector_count}")

    # Initialize LLM
    print("Initializing Groq LLM...")
    llm = ChatGroq(
        groq_api_key=GROQ_API_KEY,
        model_name=LLM_MODEL,
        temperature=0.1,
        max_tokens=1024,
    )
    print("LLM initialized")


def retrieve_documents(query: str, top_k: int = 3) -> List[dict]:
    """Retrieve relevant documents from Pinecone."""
    # Generate query embedding
    query_embedding = embedding_model.encode([query])[0].tolist()

    # Query Pinecone
    results = pinecone_index.query(
        vector=query_embedding,
        top_k=top_k,
        include_metadata=True,
    )

    documents = []
    for match in results.matches:
        metadata = match.metadata or {}
        documents.append(
            {
                "id": match.id,
                "content": metadata.get("text", ""),
                "source_file": metadata.get("source_file", ""),
                "page": metadata.get("page", 0),
                "similarity_score": match.score,
            }
        )

    return documents


def generate_answer(query: str, documents: List[dict]) -> str:
    """Generate answer using Groq LLM with retrieved context."""
    if not documents:
        return "No relevant information found to answer your question."

    # Build context from retrieved documents
    context = "\n\n".join(
        [f"Document {i + 1}: {doc['content']}" for i, doc in enumerate(documents)]
    )

    # Format and use imported prompt template
    prompt = YOGA_PROMPT_TEMPLATE.format(context=context, question=query)

    # Generate response
    response = llm.invoke(prompt)
    return response.content


def extract_sources(documents: List[dict]) -> List[str]:
    """Extract source information from documents."""
    sources = []
    for doc in documents:
        source = doc.get("source_file", "")
        page = doc.get("page", 0)
        if source:
            sources.append(f"{source} (page {page})")
    return sources


def extract_poses(answer: str) -> List[dict]:
    """Extract yoga poses mentioned in the answer.

    This is a simple implementation that can be enhanced with NER
    or a yoga poses database.
    """
    # Common yoga poses keywords
    pose_keywords = [
        "downward dog", "adho mukha svanasana",
        "tree pose", "vrksasana",
        "warrior", "virabhadrasana",
        "child pose", "balasana",
        "cobra", "bhujangasana",
        "mountain pose", "tadasana",
        "lotus", "padmasana",
        "triangle", "trikonasana",
        "plank", "phalakasana",
        "bridge", "setu bandhasana",
        "corpse pose", "savasana",
    ]

    poses = []
    answer_lower = answer.lower()

    for pose in pose_keywords:
        if pose in answer_lower:
            poses.append({
                "name": pose.title(),
                "confidence": 0.8
            })

    return poses[:3]  # Return top 3


@app.get("/")
def root():
    """Root endpoint."""
    return {
        "message": "Yoga RAG API",
        "docs": "/docs",
        "endpoints": {"query": "/query"},
    }


@app.get("/health")
def health():
    """Health check endpoint."""
    return {"status": "healthy"}


@app.post("/query", response_model=QueryResponse)
def query_endpoint(request: QueryRequest):
    """Query the yoga knowledge base.

    Args:
        request: QueryRequest with question string

    Returns:
        QueryResponse with generated answer and metadata
    """
    try:
        # Retrieve relevant documents
        documents = retrieve_documents(request.question, request.top_k)

        # Generate answer
        answer = generate_answer(request.question, documents)

        # Build response
        sources = extract_sources(documents)
        poses = extract_poses(answer)

        return QueryResponse(
            id=str(uuid.uuid4()),
            answer=answer,
            sources=sources,
            isUnsafe=False,  # Can be enhanced with safety check
            poses=poses,
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/feedback")
def feedback_endpoint(request: FeedbackRequest):
    """Handle user feedback.

    Args:
        request: FeedbackRequest with questionId and feedback type

    Returns:
        Success message
    """
    # Log feedback (can be extended to store in database)
    print(f"Feedback received: questionId={request.questionId}, feedback={request.feedback}")
    return {"message": "Feedback received successfully"}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=PORT)