"""FastAPI application for Yoga RAG Query API.

This API allows users to query the Pinecone vector database
and get answers generated by Groq LLM based on retrieved context.
"""

import os
import threading
import uuid
from typing import List, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from langchain_groq import ChatGroq
from pinecone import Pinecone
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer

# Load environment variables
load_dotenv()

# Initialize FastAPI app
app = FastAPI(
    title="Yoga RAG API",
    description="Query API for Yoga knowledge base using Pinecone vector search",
    version="1.0.0",
)

# Add CORS middleware for frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configuration
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME", "yoga-rag")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
LLM_MODEL = "llama-3.3-70b-versatile"

# Global clients (initialized lazily)
_embedding_model: Optional[SentenceTransformer] = None
_pinecone_index = None
_llm = None
_lock = threading.Lock()
_initialized = False


def initialize_models():
    """Initialize models lazily."""
    global _embedding_model, _pinecone_index, _llm, _initialized

    if _initialized:
        return

    with _lock:
        if _initialized:
            return

        print("Loading embedding model...")
        _embedding_model = SentenceTransformer(EMBEDDING_MODEL)
        print(f"Embedding model loaded: {EMBEDDING_MODEL}")

        print("Connecting to Pinecone...")
        pc = Pinecone(api_key=PINECONE_API_KEY)
        _pinecone_index = pc.Index(PINECONE_INDEX_NAME)
        stats = _pinecone_index.describe_index_stats()
        print(f"Connected to Pinecone index: {PINECONE_INDEX_NAME}")
        print(f"Total vectors: {stats.total_vector_count}")

        print("Initializing Groq LLM...")
        _llm = ChatGroq(
            groq_api_key=GROQ_API_KEY,
            model_name=LLM_MODEL,
            temperature=0.1,
            max_tokens=1024,
        )
        print("LLM initialized")

        _initialized = True


class QueryRequest(BaseModel):
    question: str
    top_k: int = 5


class FeedbackRequest(BaseModel):
    questionId: str
    feedback: str


class QueryResponse(BaseModel):
    id: str
    answer: str
    sources: List[str]
    isUnsafe: bool
    poses: List[dict] = []


def retrieve_documents(query: str, top_k: int = 5) -> List[dict]:
    """Retrieve relevant documents from Pinecone."""
    if _pinecone_index is None or _embedding_model is None:
        raise HTTPException(status_code=503, detail="Models not initialized yet")

    # Generate query embedding
    query_embedding = _embedding_model.encode([query])[0].tolist()

    # Query Pinecone
    results = _pinecone_index.query(
        vector=query_embedding,
        top_k=top_k,
        include_metadata=True,
    )

    documents = []
    for match in results.matches:
        metadata = match.metadata or {}
        documents.append(
            {
                "id": match.id,
                "content": metadata.get("text", ""),
                "source_file": metadata.get("source_file", ""),
                "page": metadata.get("page", 0),
                "similarity_score": match.score,
            }
        )

    return documents


def generate_answer(query: str, documents: List[dict]) -> str:
    """Generate answer using Groq LLM with retrieved context."""
    if _llm is None:
        raise HTTPException(status_code=503, detail="Models not initialized yet")

    if not documents:
        return "No relevant information found to answer your question."

    # Build context from retrieved documents
    context = "\n\n".join(
        [f"Document {i + 1}: {doc['content']}" for i, doc in enumerate(documents)]
    )

    # Create prompt
    prompt = f"""You are a knowledgeable yoga instructor. Use the following context from yoga documents to answer the user's question.

Context:
{context}

Question: {query}

Provide a clear, concise answer based on the context above. If the context doesn't contain relevant information, say so."""

    # Generate response
    response = _llm.invoke(prompt)
    return response.content


def extract_sources(documents: List[dict]) -> List[str]:
    """Extract source information from documents."""
    sources = []
    for doc in documents:
        source = doc.get("source_file", "")
        page = doc.get("page", 0)
        if source:
            sources.append(f"{source} (page {page})")
    return sources


def extract_poses(answer: str) -> List[dict]:
    """Extract yoga poses mentioned in the answer."""
    pose_keywords = [
        "downward dog", "adho mukha svanasana",
        "tree pose", "vrksasana",
        "warrior", "virabhadrasana",
        "child pose", "balasana",
        "cobra", "bhujangasana",
        "mountain pose", "tadasana",
        "lotus", "padmasana",
        "triangle", "trikonasana",
        "plank", "phalakasana",
        "bridge", "setu bandhasana",
        "corpse pose", "savasana",
    ]

    poses = []
    answer_lower = answer.lower()

    for pose in pose_keywords:
        if pose in answer_lower:
            poses.append({
                "name": pose.title(),
                "confidence": 0.8
            })

    return poses[:3]


@app.get("/")
def root():
    """Root endpoint."""
    return {
        "message": "Yoga RAG API",
        "docs": "/docs",
        "endpoints": {"query": "/query", "health": "/health"},
    }


@app.get("/health")
def health():
    """Health check endpoint."""
    if not _initialized:
        # Start initialization in background on first health check
        threading.Thread(target=initialize_models, daemon=True).start()
        return {"status": "initializing"}
    return {"status": "healthy"}


@app.post("/query", response_model=QueryResponse)
def query_endpoint(request: QueryRequest):
    """Query the yoga knowledge base."""
    try:
        # Ensure models are initialized
        initialize_models()

        # Retrieve relevant documents
        documents = retrieve_documents(request.question, request.top_k)

        # Generate answer
        answer = generate_answer(request.question, documents)

        # Build response
        sources = extract_sources(documents)
        poses = extract_poses(answer)

        return QueryResponse(
            id=str(uuid.uuid4()),
            answer=answer,
            sources=sources,
            isUnsafe=False,
            poses=poses,
        )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/feedback")
def feedback_endpoint(request: FeedbackRequest):
    """Handle user feedback."""
    print(f"Feedback received: questionId={request.questionId}, feedback={request.feedback}")
    return {"message": "Feedback received successfully"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
